- id: cargo-fmt
  name: cargo fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: rust
  types: [rust]
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: rust
  types: [rust]
  pass_filenames: false
- id: cargo-clippy
  name: cargo clippy
  description: Lint Rust sources with Clippy.
  entry: cargo clippy
  language: rust
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
- id: cargo-test
  name: cargo test
  description: Run tests
  entry: cargo test
  language: rust
  types: [rust]
  pass_filenames: false
